name: jira_watcher
description: "A Jira client, built to easily overview recent updates."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  diff_match_patch: ^0.4.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_json: ^0.0.4
  flutter_svg: ^2.0.9
  flutter_web_auth_2: ^4.1.0
  html: ^0.15.6
  http: ^1.4.0
  material_symbols_icons: ^4.2815.1
  mime: ^2.0.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.1
  super_clipboard: ^0.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.12

flutter:
  uses-material-design: true
  assets:
    - assets/

msix_config:
  display_name: Jira Watcher
  publisher_display_name: github@Este2013
  identity_name: este.custom-tools.jira-watcher
  msix_version: 1.0.0.0
  logo_path: assets/app_icon.png
  capabilities: internetClient
