//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

library openapi.api;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:collection/collection.dart';
import 'package:http/http.dart';
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/api_key_auth.dart';
part 'auth/oauth.dart';
part 'auth/http_basic_auth.dart';
part 'auth/http_bearer_auth.dart';

part 'api/backlog_api.dart';
part 'api/board_api.dart';
part 'api/builds_api.dart';
part 'api/deployments_api.dart';
part 'api/dev_ops_components_api.dart';
part 'api/development_information_api.dart';
part 'api/epic_api.dart';
part 'api/feature_flags_api.dart';
part 'api/issue_api.dart';
part 'api/operations_api.dart';
part 'api/remote_links_api.dart';
part 'api/security_information_api.dart';
part 'api/sprint_api.dart';

part 'model/associations.dart';
part 'model/author.dart';
part 'model/avatar_urls_bean.dart';
part 'model/board.dart';
part 'model/board_admins_bean.dart';
part 'model/board_config_bean.dart';
part 'model/board_create_bean.dart';
part 'model/board_filter_bean.dart';
part 'model/board_location_bean.dart';
part 'model/branch.dart';
part 'model/build_commit_reference.dart';
part 'model/build_data.dart';
part 'model/build_key.dart';
part 'model/build_ref_reference.dart';
part 'model/build_references.dart';
part 'model/change_details.dart';
part 'model/changelog.dart';
part 'model/changelog_author.dart';
part 'model/changelog_author_all_of_avatar_urls.dart';
part 'model/changelog_history_metadata.dart';
part 'model/changelog_history_metadata_all_of_actor.dart';
part 'model/changelog_history_metadata_all_of_cause.dart';
part 'model/changelog_history_metadata_all_of_generator.dart';
part 'model/changelog_items_inner.dart';
part 'model/color_bean.dart';
part 'model/column_bean.dart';
part 'model/column_config_bean.dart';
part 'model/command.dart';
part 'model/commit.dart';
part 'model/commit1.dart';
part 'model/commit2.dart';
part 'model/component.dart';
part 'model/create_board_request.dart';
part 'model/create_board_request_location.dart';
part 'model/create_sprint_request.dart';
part 'model/deployment_data.dart';
part 'model/deployment_data_associations_inner.dart';
part 'model/deployment_key.dart';
part 'model/dev_information.dart';
part 'model/entity_association.dart';
part 'model/entity_association_values_inner.dart';
part 'model/entity_error.dart';
part 'model/entity_ids.dart';
part 'model/entry.dart';
part 'model/environment.dart';
part 'model/environment_details.dart';
part 'model/epic_rank_request_bean.dart';
part 'model/epic_update_bean.dart';
part 'model/error_message.dart';
part 'model/error_message1.dart';
part 'model/error_messages.dart';
part 'model/estimate_issue_for_board_request.dart';
part 'model/estimation_config_bean.dart';
part 'model/estimation_configuration_bean.dart';
part 'model/estimation_field_bean.dart';
part 'model/exists_for_properties_response.dart';
part 'model/feature_bean.dart';
part 'model/feature_flag_data.dart';
part 'model/feature_flag_details.dart';
part 'model/feature_flag_rollout.dart';
part 'model/feature_flag_status.dart';
part 'model/feature_flag_summary.dart';
part 'model/feature_response_bean.dart';
part 'model/feature_toggle_request_bean.dart';
part 'model/field_edit_bean.dart';
part 'model/field_metadata.dart';
part 'model/field_metadata_schema.dart';
part 'model/file.dart';
part 'model/get_all_boards200_response.dart';
part 'model/get_all_boards200_response_values_inner.dart';
part 'model/get_all_boards200_response_values_inner_admins.dart';
part 'model/get_all_boards200_response_values_inner_admins_all_of_groups_inner.dart';
part 'model/get_all_boards200_response_values_inner_admins_all_of_users_inner.dart';
part 'model/get_all_boards200_response_values_inner_admins_all_of_users_inner_avatar_urls.dart';
part 'model/get_all_boards200_response_values_inner_location.dart';
part 'model/get_all_quick_filters200_response.dart';
part 'model/get_all_quick_filters200_response_values_inner.dart';
part 'model/get_board_by_filter_id200_response.dart';
part 'model/get_board_by_filter_id200_response_values_inner.dart';
part 'model/get_component_by_id200_response.dart';
part 'model/get_configuration200_response.dart';
part 'model/get_configuration200_response_column_config.dart';
part 'model/get_configuration200_response_column_config_columns_inner.dart';
part 'model/get_configuration200_response_column_config_columns_inner_statuses_inner.dart';
part 'model/get_configuration200_response_estimation.dart';
part 'model/get_configuration200_response_estimation_field.dart';
part 'model/get_configuration200_response_ranking.dart';
part 'model/get_configuration200_response_sub_query.dart';
part 'model/get_features_for_board200_response.dart';
part 'model/get_features_for_board200_response_features_inner.dart';
part 'model/get_features_for_board200_response_features_inner_permissible_estimation_types_inner.dart';
part 'model/get_incident_by_id200_response.dart';
part 'model/get_reports_for_board200_response.dart';
part 'model/get_review_by_id200_response.dart';
part 'model/group_bean.dart';
part 'model/history_metadata.dart';
part 'model/history_metadata_participant.dart';
part 'model/identifier.dart';
part 'model/incident.dart';
part 'model/incident_severity.dart';
part 'model/included_fields.dart';
part 'model/issue_assign_request_bean.dart';
part 'model/issue_bean.dart';
part 'model/issue_bean_changelog.dart';
part 'model/issue_bean_changelog_all_of_histories_inner.dart';
part 'model/issue_bean_editmeta.dart';
part 'model/issue_bean_editmeta_all_of_fields_value.dart';
part 'model/issue_bean_fields_to_include.dart';
part 'model/issue_bean_schema_value.dart';
part 'model/issue_bean_transitions_inner.dart';
part 'model/issue_bean_transitions_inner_to.dart';
part 'model/issue_bean_transitions_inner_to_all_of_scope.dart';
part 'model/issue_bean_transitions_inner_to_all_of_scope_all_of_project.dart';
part 'model/issue_bean_transitions_inner_to_all_of_scope_all_of_project_all_of_avatar_urls.dart';
part 'model/issue_bean_transitions_inner_to_all_of_scope_all_of_project_all_of_project_category.dart';
part 'model/issue_bean_transitions_inner_to_all_of_status_category.dart';
part 'model/issue_count_bean.dart';
part 'model/issue_id_or_keys_association.dart';
part 'model/issue_id_or_keys_association1.dart';
part 'model/issue_rank_request_bean.dart';
part 'model/issue_transition.dart';
part 'model/issue_update_metadata.dart';
part 'model/json_type_bean.dart';
part 'model/link_group.dart';
part 'model/link_group_header.dart';
part 'model/location_bean.dart';
part 'model/move_issues_to_backlog_for_board_request.dart';
part 'model/move_issues_to_backlog_request.dart';
part 'model/move_issues_to_board207_response.dart';
part 'model/move_issues_to_board207_response_entries_inner.dart';
part 'model/operations.dart';
part 'model/operations_workspace_ids.dart';
part 'model/page_bean_board.dart';
part 'model/page_bean_board_filter_bean.dart';
part 'model/page_bean_quick_filter_bean.dart';
part 'model/page_of_changelogs.dart';
part 'model/partial_success_bean.dart';
part 'model/partially_update_epic_request.dart';
part 'model/partially_update_epic_request_color.dart';
part 'model/pipeline.dart';
part 'model/project_details.dart';
part 'model/provider_metadata.dart';
part 'model/provider_metadata1.dart';
part 'model/pull_request.dart';
part 'model/quick_filter_bean.dart';
part 'model/rank_epics_request.dart';
part 'model/ranking_config_bean.dart';
part 'model/rejected_build.dart';
part 'model/rejected_deployment.dart';
part 'model/relation_bean.dart';
part 'model/remote_link_data.dart';
part 'model/remote_link_data_associations_inner.dart';
part 'model/remote_link_status.dart';
part 'model/reports_response_bean.dart';
part 'model/repository.dart';
part 'model/repository1.dart';
part 'model/repository_errors.dart';
part 'model/review.dart';
part 'model/reviewer.dart';
part 'model/scope.dart';
part 'model/search_results.dart';
part 'model/security_workspace_ids.dart';
part 'model/security_workspace_response.dart';
part 'model/service_id_or_keys_association.dart';
part 'model/simple_link.dart';
part 'model/software_issue_results.dart';
part 'model/sprint_bean.dart';
part 'model/sprint_create_bean.dart';
part 'model/sprint_swap_bean.dart';
part 'model/status_category.dart';
part 'model/status_details.dart';
part 'model/store_devinfo_result.dart';
part 'model/submit_builds_request.dart';
part 'model/submit_builds_response.dart';
part 'model/submit_deployment_request.dart';
part 'model/submit_deployments_response.dart';
part 'model/submit_deployments_response1.dart';
part 'model/submit_deployments_response1_details_inner.dart';
part 'model/submit_devops_components_request.dart';
part 'model/submit_devops_components_response.dart';
part 'model/submit_feature_flag_request.dart';
part 'model/submit_feature_flags_response.dart';
part 'model/submit_incidents_request.dart';
part 'model/submit_incidents_request_any_of.dart';
part 'model/submit_incidents_request_any_of1.dart';
part 'model/submit_incidents_response.dart';
part 'model/submit_operations_workspaces_request.dart';
part 'model/submit_operations_workspaces_response.dart';
part 'model/submit_remote_links202_response.dart';
part 'model/submit_remote_links202_response_rejected_remote_links_value_inner.dart';
part 'model/submit_remote_links_request.dart';
part 'model/submit_security_workspaces_request.dart';
part 'model/submit_vulnerabilities_request.dart';
part 'model/submit_vulnerabilities_response.dart';
part 'model/subquery_bean.dart';
part 'model/swap_sprint_request.dart';
part 'model/test_info.dart';
part 'model/toggle_features_request.dart';
part 'model/update_sprint_request.dart';
part 'model/updated_project_category.dart';
part 'model/user_bean.dart';
part 'model/user_bean_avatar_urls.dart';
part 'model/user_details.dart';
part 'model/vulnerability_additional_info.dart';
part 'model/vulnerability_details.dart';
part 'model/vulnerability_details_add_associations_inner.dart';
part 'model/vulnerability_severity.dart';


/// An [ApiClient] instance that uses the default values obtained from
/// the OpenAPI specification file.
var defaultApiClient = ApiClient();

const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
const _deepEquality = DeepCollectionEquality();
final _dateFormatter = DateFormat('yyyy-MM-dd');
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

bool _isEpochMarker(String? pattern) => pattern == _dateEpochMarker || pattern == '/$_dateEpochMarker/';
